RECAPTCHA_SECRET_KEY="SetAtBuildTime";
RECAPTCHA_SITE_KEY="SetAtBuildTime";
CTOP_SEND_REAL_EMAILS="SetAtBuildTime";
CTOP_EMAIL_ACCOUNT="SetAtBuildTime";
CTOP_EMAIL_PASSWORD="SetAtBuildTime";
CTOP_REDIRECT_EMAIL_FOR_TESTING="SetAtBuildTime";
